from pptx import Presentation


def create_ppt(
    summary,
    insights,
    output_path="outputs/reports/executive_summary.pptx"
):

    prs = Presentation()

    # Slide 1
    slide = prs.slides.add_slide(
        prs.slide_layouts[0]
    )

    slide.shapes.title.text = (
        "Data Storytelling Report"
    )

    slide.placeholders[1].text = (
        "Generated by AI Copilot"
    )

    # Slide 2
    slide = prs.slides.add_slide(
        prs.slide_layouts[1]
    )

    slide.shapes.title.text = (
        "Executive Summary"
    )

    slide.placeholders[1].text = summary

    # Slide 3
    slide = prs.slides.add_slide(
        prs.slide_layouts[1]
    )

    slide.shapes.title.text = (
        "Key Insights"
    )

    body = slide.placeholders[1]

    body.text = insights[0]

    for insight in insights[1:]:

        body.text += f"\n• {insight}"

    prs.save(output_path)

    return output_path